modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="sharedhealth"
version="1.3.0"
displayName="Shared Health Mod"
description='Shared health system for multiplayer'
authors="JcukengesH"
credits="JcukengesH"

[[dependencies.sharedhealthmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.sharedhealthmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"